### ISSUE TITLE
2022-06-06 todo list

### ISSUE THREAD

**Issue by ms609** [ms609/tegomoh#2]
- [x] tree to the side
- [x] Contract trace links: from, to.
- [x] SNP distance on the plot for all plot pairs
- [x] Icons for different options
